# Generated by Django 5.2.13 on 2026-04-22 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('explanation', models.TextField(blank=True, help_text='Affichée après la soumission pour aider à comprendre', verbose_name='Explication (après réponse)')),
                ('question_type', models.CharField(choices=[('SINGLE', 'Choix unique'), ('MULTIPLE', 'Choix multiples'), ('TRUE_FALSE', 'Vrai / Faux')], default='SINGLE', max_length=20, verbose_name='Type')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texte de la réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quiz_type', models.CharField(choices=[('COURSE_FINAL', 'Quiz final du cours'), ('CHAPTER', 'Quiz de chapitre')], default='CHAPTER', max_length=20, verbose_name='Type')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Score minimum pour réussir le quiz', verbose_name='Score de réussite (%)')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = pas de limite', verbose_name='Temps limite (min)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='0 = illimitées', verbose_name='Tentatives max')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='Afficher les bonnes réponses après')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.chapter', verbose_name='Chapitre (optionnel)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['course', 'chapter'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('ABANDONED', 'Abandonné')], default='IN_PROGRESS', max_length=20, verbose_name='Statut')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score obtenu')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Total points')),
                ('percentage', models.FloatField(default=0, verbose_name='Pourcentage')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer', verbose_name='Réponse sélectionnée')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.quizattempt', verbose_name='Tentative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse utilisateur',
                'verbose_name_plural': 'Réponses utilisateurs',
                'unique_together': {('attempt', 'question', 'answer')},
            },
        ),
    ]
