# Generated by Django 5.2.13 on 2026-04-22 20:10

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(default=apps.certificates.models.generate_certificate_number, help_text='Identifiant unique du certificat', max_length=30, unique=True, verbose_name='Numéro de certificat')),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID de vérification')),
                ('student_name', models.CharField(help_text='Nom au moment de la génération', max_length=200, verbose_name="Nom de l'étudiant (figé)")),
                ('course_title', models.CharField(help_text='Titre du cours au moment de la génération', max_length=200, verbose_name='Titre du cours (figé)')),
                ('instructor_name', models.CharField(max_length=200, verbose_name='Nom du formateur (figé)')),
                ('completion_percentage', models.PositiveIntegerField(default=100, verbose_name='% de complétion')),
                ('quiz_score', models.FloatField(blank=True, null=True, verbose_name='Score du quiz final (%)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Délivré le')),
                ('course_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cours terminé le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Cours')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment', verbose_name='Inscription')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'), models.Index(fields=['verification_uuid'], name='certificate_verific_2eae03_idx')],
            },
        ),
    ]
