# Generated by Django 5.2.13 on 2026-04-21 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Ex: 💻 ou nom d'une icône", max_length=50, verbose_name='Icône (emoji ou classe)')),
                ('color', models.CharField(default='#6366F1', help_text="Couleur pour l'affichage, ex: #6366F1", max_length=7, verbose_name='Couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(help_text='Résumé affiché dans les listings', max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Image de couverture')),
                ('trailer_video', models.FileField(blank=True, help_text='Vidéo de présentation (facultatif)', null=True, upload_to='courses/trailers/', verbose_name="Vidéo d'introduction")),
                ('level', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé')], default='BEGINNER', max_length=20, verbose_name='Niveau')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 pour un cours gratuit', max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Durée totale estimée en heures', verbose_name='Durée estimée (heures)')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('objectives', models.TextField(blank=True, help_text='Un objectif par ligne', verbose_name='Objectifs pédagogiques')),
                ('prerequisites', models.TextField(blank=True, help_text='Un prérequis par ligne', verbose_name='Prérequis')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Catégorie')),
                ('instructor', models.ForeignKey(limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('PDF', 'PDF'), ('TEXT', 'Texte'), ('MIXED', 'Contenu mixte')], default='VIDEO', max_length=20, verbose_name='Type de contenu')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube, Vimeo, etc. (alternative au fichier)', verbose_name='URL vidéo externe')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='Fichier PDF')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Durée estimée de la leçon en minutes', verbose_name='Durée (minutes)')),
                ('is_free_preview', models.BooleanField(default=False, help_text='Accessible sans inscription', verbose_name='Aperçu gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='courses_cou_status_ee4b06_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'order')},
        ),
    ]
